examples/python/rt_webapp/rt_webapp/urls.py
# Owen Gallagher
# 2021-09-03
# rt webapp url config

from django.urls import path

from . import views

app_name='rt_webapp'

urlpatterns = [
    # root --> index
    path(route='', view=views.index, name='index'),
    
    # new_tag form handler
    path(route='new_tag', view=views.new_tag, name='new_tag')
]

examples/python/rt_webapp/rt_webapp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # naked routes point to rt webapp
    path('', include('rt_webapp.urls'))
]

examples/python/rt_webapp/rt_webapp/models.py
# Owen Gallagher
# 2021-09-03
# rt webapp persistent rel-db compatible classes

from random import random
from django.db import models

import relational_tags as rt

# Create your models here.

class RtEntityModel(models.Model):
    """Encapsulate rt.RelationalEntity as a db model.
    """
    
    entity_json:str = models.TextField(
        blank=False,
        unique=True,
        help_text='Relational entity json string.'
    )
    
    @classmethod
    def create(cls, entity:rt.RelationalEntity) -> 'RtEntityModel':
        """Create RtEntityModel instance.
        """
        
        return cls(entity_json=str(entity))
    # end create
    
    def __str__(self):
        return self.entity_json
    # end __str__
# end RtEntityModel

class RtTagModel(models.Model):
    """Encapsulate rt.RelationalTag as a db model.
    
    Note that it would make much more sense to use the actual fields in a RelationalTag for creating
    relationships between tags and entities in the database.
    """
    
    tag_json:str = models.CharField(
        max_length=256,
        blank=False,
        unique=True,
        help_text='Relational tag json string.'
    )
    tag_name:str = models.CharField(
        max_length=128,
        blank=False,
        unique=True,
        help_text='Relational tag name.',
        default=str(random())
    )
    
    @classmethod
    def create(cls, tag:rt.RelationalTag) -> 'RtTagModel':
        """Create RtTagModel instance.
        """
        
        return cls(tag_json=str(tag),tag_name=tag.name)
    # end create
    
    def __str__(self):
        return self.tag_json
    # end __str__
# end RtTagModel

examples/python/rt_webapp/rt_webapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .models import RtTagModel, RtEntityModel

import relational_tags as rt

# module vars

tag_models = []

# views

def index(request):
    """relational tags webapp index page.
    """
    
    # get tag connections
    connections = {}
    for conn_type in rt.RelationalTagConnection._TAG_TAG_TYPES:
        connections[conn_type] = rt.RelationalTagConnection.type_to_str(conn_type)
    # end for conn_type
    
    # pass data to template gui via context
    context = {
        'tags': [tag for tag in rt.all_tags.values()],
        'tags_json': rt.save_json(),
        'connections': connections
    }
    
    # render template
    return render(request, 'rt_webapp/index.html', context)
# end index

def new_tag(request):
    """relational tags webapp new_tag form handler
    """
    
    # create new tag
    new_tag = request.POST['tag_name']
    # convert new tag to RelationalTag
    try:
        # get existing tag
        new_tag = rt.get(name=new_tag, new_if_missing=False)
        
    except rt.RelationalTagError:
        # add new tag to database
        new_tag = rt.new(name=new_tag)
        
        new_tag_model = RtTagModel.create(tag=new_tag)
        new_tag_model.save()
    
    tag_target = request.POST['tag_target']
    tag_connection = request.POST['tag_connection']
    if (tag_target != '' and tag_connection != ''):
        # convert tag target to RelationalTag
        try:
            # get existing target tag
            tag_target = rt.get(name=tag_target, new_if_missing=False)
            
        except rt.RelationalTagError:
            # save new target tag to database
            tag_target = rt.new(name=tag_target)
            RtTagModel.create(tag=tag_target).save()
        
        # connect tag to target
        connection = rt.connect(
            tag_or_connection=new_tag, 
            target=tag_target, 
            connection_type=tag_connection
        )
        print(connection)
        
        # save new connectionto db
        new_tag_model = RtTagModel.objects.get(tag_name=new_tag.name)
        new_tag_model.tag_json = str(new_tag)
        new_tag_model.save()
        
        tag_target_model = RtTagModel.objects.get(tag_name=tag_target.name)
        tag_target_model.tag_json = str(tag_target)
        new_tag_model.save()
    # end if tag_target and tag_connection
    
    # direct back to index page
    return HttpResponseRedirect('/')
# end new_tag

# main

def main():
    rt.config(is_case_sensitive=False)
    
    # load relational tags from db
    tag_models = RtTagModel.objects.all()
    
    for tag_model in tag_models:
        rt.load_tag(str(tag_model))
    # end for tag_model in tag_models
# end main

main()

examples/python/rt_webapp/rt_webapp/templates/rt_webapp/index.html
<!doctype html>
<head>
	<!-- metadata -->
	
    <meta charset="utf-8"/>
    <!--scales viewport depending on worldspace device width-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	
    <meta name="description" content="Relational tags webapp index page."/>
    <meta name="author" content="Owen Gallagher <github.com/ogallagher>"/>
	<meta name="page-name" content="index.html"/>
	
	<title>Relational Tags Python Example Webapp</title>
	
	<!-- django tags and filters -->
	{% load filters %}
	{% load static %}
	
	<!-- bootstrap -->
	
	<link 
		href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" 
		rel="stylesheet" 
		integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" 
		crossorigin="anonymous">
	
	<!-- jquery -->
	<script 
		src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js" 
		type="text/javascript"
		integrity="sha512-6ORWJX/LrnSjBzwefdNUyLCMTIsGoNP6NftMy2UAm1JBm6PRZCO1d7OHBStWpVFZLO+RerTvqX/Z9mBFfCJZ4A==" 
		crossorigin="anonymous" 
		referrerpolicy="no-referrer"></script>
	
	<!-- paperjs -->
	<script 
		src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.15/paper-core.min.js" 
		type="text/javascript"
		integrity="sha512-n8kxMM6jgawwNHl1HJmOXz+l8bMYaq0SrYrbCijlUnUUNXuD4ajzKmdXSTFarH3PViz54jfiSNUUAfTOhIDmRg==" 
		crossorigin="anonymous" 
		referrerpolicy="no-referrer"
		async></script>
	
	<!-- visualizer -->
	<script type="text/javascript" src="{% static 'rt_webapp/tag_node.js' %}"></script>
	<script type="text/javascript" src="{% static 'rt_webapp/connection_line.js' %}"></script>
	<script type="text/javascript" src="{% static 'rt_webapp/visualizer.js' %}"></script>
	
	<script type="text/javascript">
		// expose tags to index.js (convert to javascript dictionary)
		let index_context = {
			tags_object: {{tags_json|safe}}
		}
	</script>
	<script type="text/javascript" src="{% static 'rt_webapp/index.js' %}"></script>
</head>
<body>
	<article class="container">
		<section class="my-4">
			<h2>All Tags</h2>
			{% if tags %}
				<ul>
					{% for tag in tags %}
						<li>
							<span>{{tag.name}}</span>
							<ul>
								{% for target,connection in tag.connections.items %}
									<li><span>{{connection.type|rt_conn_type_to_str}}</span> &rarr; <span>{{connection.target.name}}</span></li>
								{% endfor %}
							</ul>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>No tags found.</p>
			{% endif %}
		</section>
		
		<section class="my-4">
			<h2>Create or Update a Tag</h2>
			<form  method="post" action="{% url 'rt_webapp:new_tag' %}">
				<!-- cross site request forgery protection token -->
				{% csrf_token %}
		
				<fieldset>
					<datalist id="tag-name-options">
						{% for tag in tags %}
							<option value="{{tag.name}}"></option>
						{% endfor %}
					</datalist>
			
					<div class="row mb-2">
						<label class="form-label col-auto" for="tag-name">tag name</label>
						<div class="col">
							<input class="form-control" type="text" id="tag-name" list="tag-name-options" placeholder="new-tag" name="tag_name"/>
						</div>
					</div>
			
					<div class="row mb-2">
						<label class="form-label col-auto" for="tag-target">relates to</label>
						<div class="col">
							<input class="form-control" type="text" id="tag-target" list="tag-name-options" placeholder="tag-target" name="tag_target"/>
						</div>
				
						<label class="form-label col-auto" for="tag-connection">as</label>
						<div class="col">
							<select class="form-select" id="tag-connection" name="tag_connection">
								{% for key,value in connections.items %}
									<option value="{{key}}">{{value}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
				</fieldset>
		
				<input type="submit" class="form-control btn-primary mb-2" value="submit"/>
			</form>
		</section>
		
		<section class="my-4">
			<h2>Relational Tags Visualizer</h2>
			<canvas id="visualizer-canvas" class="w-100 bg-dark"></canvas>
		</section>
	</article>
	
	<footer class="container-fluid bg-dark text-light py-4">
		<div class="row justify-content-end">
			<div class="col-auto">CC BY-SA</div>
			<div class="col-auto">
				<a href="https://github.com/ogallagher" class="text-light">Owen Gallagher</a>
			</div>
		</div>
	</footer>
</body>